
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/adk-trade', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/adk-trade']
- name: 'hashicorp/terraform:1.8.0'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    terraform init
    terraform apply -auto-approve -var="project_id=$PROJECT_ID"
